[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos_ocp_news_plugin"
dynamic = ["version"]
description = "OCP news feed stream extractor plugin"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "ocp", "plugin"]
dependencies = [
    "ovos-plugin-manager>=2.1.0,<3.0.0",
    "ovos-ocp-rss-plugin>=0.0.2,<1.0.0",
    "ovos-ocp-m3u-plugin>=0.0.1,<1.0.0",
    "pytz",
    "beautifulsoup4"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-ocp-news-plugin"

[project.entry-points."opm.ocp.extractor"]
"ovos-ocp-news-plugin" = "ovos_ocp_news_plugin:OCPNewsExtractor"

[tool.setuptools.dynamic]
version = {attr = "ovos_ocp_news_plugin.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ovos_ocp_news_plugin*"]
